// 
//  ListUsersInteractor.swift
//  Messenger
//
//  Created by Canh Tran Wizeline on 3/10/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ListUsersInteractor {
    // MARK: - Private Properties

    private let networkClient: NetworkRequestable

    // MARK: - LifeCycle

    init(networkClient: NetworkRequestable = NetworkClient()) {
        self.networkClient = networkClient
    }
}

// MARK: - ListUsersInteractorInterface

extension ListUsersInteractor: ListUsersInteractorInterface {
    func fetchListUsers(lastId: Int, completion: @escaping (Result<[User], NetworkError>) -> Void) {
        networkClient.fetch(endPoint: ListUsersEndpoint.fetchListUser(lastId: lastId), type: [User].self) { (result) in
            DispatchQueue.main.async {
                completion(result)
            }
        }
    }
}
