// 
//  ListUsersInterfaces.swift
//  Messenger
//
//  Created by Canh Tran Wizeline on 3/10/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

// Dependency
protocol ListUsersDependencyInterface {
    func makeListUsersView() -> ViewInterface
}

// Router
protocol ListUsersRouterInterface: NavigationRouterInterface {
    func openDirectMessage(with user: User)
}

// ViewController
protocol ListUsersViewInterface: ViewInterface {
    func reloadData()
    func setLoadingVisible(_ visible: Bool)
}

// Presenter
protocol ListUsersPresenterInterface: PresenterInterface {
    func numberOfUsers() -> Int
    func userAtIndex(index: Int) -> User?
    func refreshListUsers()
    func fetchListUsers()
    func openDirectMessageAt(index: Int)
}

// Interactor
protocol ListUsersInteractorInterface {
    func fetchListUsers(lastId: Int, completion: @escaping (Result<[User], NetworkError>) -> Void)
}
