// 
//  DirectMessagesDependency.swift
//  Messenger
//
//  Created by Canh Tran Wizeline on 3/10/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DirectMessagesDependency: DirectMessagesDependencyInterface {
    // MARK: - Module Setup

    func makeDirectMessagesView(with user: User) -> DirectMessagesViewInterface {
        let view = DirectMessagesViewController()
        
        let interactor = DirectMessagesInteractor()
        let router = DirectMessagesRouter(rootController: view)

        let presenter = DirectMessagesPresenter(view: view,
                                                interactor: interactor,
                                                router: router,
                                                user: user)
        view.presenter = presenter
        
        return view
    }
}
