// 
//  DirectMessagesInterfaces.swift
//  Messenger
//
//  Created by Canh Tran Wizeline on 3/10/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

// Dependency
protocol DirectMessagesDependencyInterface {
    func makeDirectMessagesView(with user: User) -> DirectMessagesViewInterface
}

// Router
protocol DirectMessagesRouterInterface: ViewRouterInterface {
}

// ViewController
protocol DirectMessagesViewInterface: ViewInterface {
    func reloadData()
}

// Presenter
protocol DirectMessagesPresenterInterface: PresenterInterface {
    func getUserName() -> String
    func numberOfMessages() -> Int
    func messageAtIndex(index: Int) -> Message?
    func fetchListMessages()
    func createNewMessage(with text: String)
}

// Interactor
protocol DirectMessagesInteractorInterface {
    func fetchListMessages(with userId: Int, completion: @escaping (Result<[Message], NetworkError>) -> Void)
    func createNewMessage(_ message: Message, user: User, completion: @escaping (Result<Message, NetworkError>) -> Void)
    func storeMessages(messages: [Message], userId: Int)
}
