// 
//  DirectMessagesRouter.swift
//  Messenger
//
//  Created by Canh Tran Wizeline on 3/10/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DirectMessagesRouter: ViewRouter {
}

// MARK: - DirectMessagesRouterInterface

extension DirectMessagesRouter: DirectMessagesRouterInterface {
}
