// ___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

protocol ___VARIABLE_moduleName___DependencyInterface {
    func make___VARIABLE_moduleName___View() -> ViewInterface
}

protocol ___VARIABLE_moduleName___RouterInterface: NavigationRouterInterface {
}

protocol ___VARIABLE_moduleName___ViewInterface: ViewInterface {
}

protocol ___VARIABLE_moduleName___PresenterInterface: PresenterInterface {
}

protocol ___VARIABLE_moduleName___InteractorInterface {
}
